CREATE TABLE "financial_ratios" (
"id" INTEGER,
  "company_id" TEXT,
  "year" INTEGER,
  "broad_sector" TEXT,
  "net_profit_margin_pct" REAL,
  "operating_profit_margin_pct" REAL,
  "operating_profit_margin_variance_pct" REAL,
  "return_on_equity_pct" REAL,
  "return_on_capital_employed_pct" REAL,
  "return_on_assets_pct" REAL,
  "roce_sector_median_pct" REAL,
  "roce_vs_sector_pct" REAL,
  "debt_to_equity" REAL,
  "high_leverage_flag" INTEGER,
  "interest_coverage" REAL,
  "icr_label" TEXT,
  "icr_warning_flag" INTEGER,
  "net_debt_cr" REAL,
  "asset_turnover" REAL,
  "free_cash_flow_cr" REAL,
  "capex_cr" REAL,
  "capex_intensity_pct" REAL,
  "capex_intensity_label" TEXT,
  "fcf_conversion_rate_pct" REAL,
  "earnings_per_share" REAL,
  "book_value_per_share" REAL,
  "dividend_payout_ratio_pct" REAL,
  "total_debt_cr" REAL,
  "cash_from_operations_cr" REAL,
  "cfo_pat_ratio" REAL,
  "cfo_quality_5yr" REAL,
  "cfo_quality_label" TEXT,
  "cfo_sign" TEXT,
  "cfi_sign" TEXT,
  "cff_sign" TEXT,
  "capital_allocation_pattern" TEXT,
  "revenue_cagr_3yr" REAL,
  "revenue_cagr_3yr_flag" TEXT,
  "revenue_cagr_5yr" REAL,
  "revenue_cagr_5yr_flag" TEXT,
  "revenue_cagr_10yr" REAL,
  "revenue_cagr_10yr_flag" TEXT,
  "pat_cagr_3yr" REAL,
  "pat_cagr_3yr_flag" TEXT,
  "pat_cagr_5yr" REAL,
  "pat_cagr_5yr_flag" TEXT,
  "pat_cagr_10yr" REAL,
  "pat_cagr_10yr_flag" TEXT,
  "eps_cagr_3yr" REAL,
  "eps_cagr_3yr_flag" TEXT,
  "eps_cagr_5yr" REAL,
  "eps_cagr_5yr_flag" TEXT,
  "eps_cagr_10yr" REAL,
  "eps_cagr_10yr_flag" TEXT,
  "composite_quality_score" REAL
);

CREATE UNIQUE INDEX idx_financial_ratios_company_year
            ON financial_ratios(company_id, year)
            ;
